# -*- coding: utf-8 -*-
"""01_23341006_23301589.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aHhPaQWKql4NszkwNY8yoCNHz5ArPZ0b
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.multiclass import OneVsRestClassifier
from sklearn.metrics import roc_curve, auc
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay, classification_report, precision_score, recall_score
from sklearn.metrics import roc_curve, auc
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import RobustScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.utils.class_weight import compute_class_weight
from imblearn.over_sampling import SMOTE

df = pd.read_csv('/content/academic_success_dataset.csv')
#df = pd.read_csv('/content/disease_classification_dataset.csv')

data = df[df.columns[:25]]

print(data.shape)
data.head(5)

"""# ** DATA ANALYSIS **

"""

print('Shape of the dataset is {}. This dataset contains {} rows and {} columns. \n'.format(data.shape,data.shape[0],data.shape[1]))

numerical_data = data.select_dtypes(include='number')

#append the features of numerical_data to list
numerical_features=numerical_data.columns.tolist()

print(f'There are {len(numerical_features)} numerical features:', '\n')
print(numerical_features, '\n')


categorical_data=data.select_dtypes(include= 'object')

#append the features of categorical_data to list
categorical_features=categorical_data.columns.tolist()

print(f'There are {len(categorical_features)} catagorical features:', '\n')
print(categorical_features)

"""## Describe Data"""

numerical_data.describe().T

categorical_data.describe().T

"""## Variance and Skew"""

numerical_data.var()

numerical_data.skew()

"""Application mode, Previous qualification (grade), Mother's qualification, Father's qualification, Displaced, Unemployment rate, Inflation rate, GDP are **[ Fairly symmetrical ]**

Admission grade, Gender are **[ Moderately skewed ]**

Marital status, Application order, Course, Daytime/evening attendance\t, Previous qualification, Nacionality, Mother's occupation, Father's occupation, Educational special needs, Debtor, Tuition fees up to date, Scholarship holder, Age at enrollment, International are **[ Highly skewed ]**

## Bar Charts
"""

numerical_data.hist(figsize=(12,12),bins=20)
plt.show()

numerical_data.nunique()

numerical_data.isnull().sum()

numeric_cols = data.select_dtypes(include=['int64', 'float64']).columns

# Set up the figure
plt.figure(figsize=(20, 30))

# Plot boxplots for each numerical feature including the target variable 'OUTCOME'
for i, col in enumerate(numeric_cols, 1):
    plt.subplot(len(numeric_cols), 1, i)
    sns.boxplot(x=data[col], color='skyblue')
    plt.title(f'Boxplot of {col}', fontsize=12)
    plt.tight_layout()

plt.show()

"""## Catagorical Features"""

unique_counts=categorical_data.nunique()
unique_counts

categorical_data['Target'].value_counts().sort_index().plot(kind='bar', rot=0, xlabel=col,ylabel='count')
plt.show()

"""## Corrolation and Heatmap"""

correlation_matrix = numerical_data.corr()
correlation_matrix

plt.figure(figsize=(12, 12))
sns.heatmap(correlation_matrix, annot=True, cmap='YlGnBu', fmt='.1f', linewidths=0.3)
plt.show()

fig, ax = plt.subplots(3,1, figsize=(10, 20))
## Correlation coefficient using different methods
numerical_data['Target'] = data['Target'].astype('category').cat.codes

corr1 = numerical_data.corr('pearson')[['Target']].sort_values(by='Target', ascending=False)
corr2 = numerical_data.corr('spearman')[['Target']].sort_values(by='Target', ascending=False)
corr3 = numerical_data.corr('kendall')[['Target']].sort_values(by='Target', ascending=False)

#setting titles for each plot
ax[0].set_title('Pearson method')
ax[1].set_title('spearman method')
ax[2].set_title('Kendall method')

## Generating heatmaps of each methods
sns.heatmap(corr1, ax=ax[0], annot=True)
sns.heatmap(corr2, ax=ax[1], annot=True)
sns.heatmap(corr3, ax=ax[2], annot=True)

"""## Check imbalance in the data"""

class_counts=data.groupby("Target").size()

columns=['Target','count','percentage']
outcome = class_counts.index.tolist()
count=list()
percentage=list()

#Calculate the percentage of each value of the OUTCOME variable from total
for val in range(3):
    count.append(class_counts[val])
    percent=(class_counts[val]/class_counts.sum())*100
    percentage.append(percent)

# Convert the calulated values into a dataframe
imbalance_df=pd.DataFrame(list(zip(outcome,count,percentage)),columns=columns)
imbalance_df

sns.barplot(data=imbalance_df,x=imbalance_df['Target'],y=imbalance_df['percentage'])
plt.show()

numerical_data.plot(kind='density',figsize=(14,14),subplots=True,layout=(9,3),title="Density plot of Numerical features",sharex=False)
plt.show()

"""# **Pre-Process**"""

#drop columns with less importance
data = data.drop(columns =['Nacionality'])
data = data.drop(columns =["Mother's occupation"])
data = data.drop(columns =['Age at enrollment'])
data = data.drop(columns =['Application mode'])
data = data.drop(columns =['Gender'])
data = data.drop(columns =['Debtor'])

#filter null rows
data = data.dropna(axis = 0, subset = ['Target', "Mother's qualification",
                                       "Father's qualification", 'Course',  'International'])
#impute with mean
impute = SimpleImputer(missing_values=np.nan, strategy='mean')  #Finding the average of the values and putting it into NaN
mean_coloums = ['Admission grade', 'Unemployment rate', 'GDP', 'Inflation rate', 'Previous qualification (grade)']

data[mean_coloums] = impute.fit_transform(data[mean_coloums])

#impute with mode
mode_columns = ['Marital status','Application order', "Father's occupation",
      'Previous qualification', 'Tuition fees up to date', 'Daytime/evening attendance\t',
      'Displaced', 'Educational special needs', 'Scholarship holder' ]

mode_imputer = SimpleImputer(strategy='most_frequent')
data[mode_columns] = mode_imputer.fit_transform(data[mode_columns])

print(data.shape)
data.isnull().sum()

#encode
data['Target'] = data['Target'].map({'Graduate':2,'Enrolled':0,'Dropout':1})

"""# **Supervised Learning**

## ** K-Nearest Neighbors (KNN)**
"""

from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import RobustScaler


x = data.drop(columns=["Target"])
y = data["Target"]

scaler = RobustScaler()
cols = [ 'Course', "Mother's qualification", "Father's qualification","Admission grade", "Previous qualification (grade)", "Previous qualification"]
scaled_x = scaler.fit_transform(x[cols])

X_train, X_test, y_train, y_test = train_test_split(scaled_x, y, test_size = 0.2, stratify = y, random_state=0)

knn = KNeighborsClassifier(n_neighbors=5)

knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)
from sklearn.metrics import accuracy_score

accuracy_knn = accuracy_score(y_test, y_pred)
print("Accuracy using sklearn: {:.2f}".format(accuracy_knn))
class_rep_knn = classification_report(y_test, y_pred, target_names=['Dropout', 'Graduate', 'Enrolled'])
print("\nClassification Report (KNN):\n", class_rep_knn)

ConfusionMatrixDisplay.from_estimator(knn, X_test, y_test, cmap="Blues",
                                      display_labels=['Dropout', 'Graduate', 'Enrolled'])
plt.title("Confusion Matrix – KNN (target: Location)")
plt.tight_layout();
plt.show()

y_pred_knn = knn.predict_proba(X_test)[:, 1]

"""## **Logistic Regression**"""

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler

x = data.drop(columns=["Target"])
y = data["Target"]

scaler = RobustScaler()
cols = [ 'Course', "Mother's qualification", "Father's qualification", "Admission grade", "Previous qualification (grade)", "Previous qualification"]
scaler.fit(x[cols])
scaled_x = scaler.transform(x[cols])

X_train, X_test, y_train, y_test = train_test_split(scaled_x, y, test_size = 0.2, stratify = y, random_state=0)


log_reg = LogisticRegression(max_iter=1000)
log_reg.fit(X_train, y_train)
y_pred = log_reg.predict(X_test)


accuracy_log = accuracy_score(y_test, y_pred)
print("Accuracy using sklearn: {:.2f}".format(accuracy_log))
class_rep_logistic = classification_report(y_test, y_pred, target_names=['Dropout', 'Graduate', 'Enrolled'])
print("\nClassification Report (LR):\n", class_rep_logistic)

ConfusionMatrixDisplay.from_estimator(log_reg, X_test, y_test, cmap="Blues",
                                      display_labels=['Dropout', 'Graduate', 'Enrolled'])
plt.title("Confusion Matrix – LR (target: Location)")
plt.tight_layout();
plt.show()

y_pred_logistic = log_reg.predict_proba(X_test)[:, 1]

"""# **K-Means Clustering**"""

from sklearn.cluster import KMeans
from sklearn.decomposition import PCA

data_copy = data.drop(columns=["Target"])

scaler = RobustScaler()
cols = ['Course', "Mother's qualification", "Father's qualification",
        "Admission grade", "Previous qualification (grade)", "Previous qualification"]
scaler.fit(data_copy[cols])
scaled_x = scaler.transform(data_copy[cols])

# Perform KMeans clustering
def implement_KMC(df_temp, cluster_num):
    km = KMeans(n_clusters=cluster_num, random_state=42)
    y_predicted = km.fit_predict(df_temp)
    return km, y_predicted

cluster = 3
km, y_predicted = implement_KMC(scaled_x, cluster)
data_copy["Group_cluster"] = y_predicted

km.cluster_centers_

pca = PCA(n_components=2)
pca_components = pca.fit_transform(scaled_x)

# Plotting the PCA results
plt.figure(figsize=(8, 8))
plt.scatter(pca_components[:, 0], pca_components[:, 1], c=data_copy["Group_cluster"], cmap='viridis', s=50)


centroids = pca.transform(km.cluster_centers_)
# Plot the centroids
plt.scatter(centroids[:, 0], centroids[:, 1], c='red', marker='X', s=200)

plt.title('PCA of Scaled Data with KMeans Clusters and Centroids')
plt.xlabel('PCA Component 1')
plt.ylabel('PCA Component 2')
plt.legend()
plt.colorbar(label='Cluster')
plt.grid(True)
plt.show()

k_range = range(1,10)
SSE = []
for k in k_range:
  km = KMeans(n_clusters= k)
  km.fit(scaled_x)   #using the first mockup dataset
  SSE.append(km.inertia_)

print(SSE)

plt.xlabel("K")
plt.ylabel("Sum of Squarred Error [SSE]")
plt.plot(k_range,SSE)

"""# **Neural Network**"""

from tensorflow.keras import Sequential
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.losses import SparseCategoricalCrossentropy
from sklearn.utils.class_weight import compute_class_weight
from imblearn.over_sampling import SMOTE

x = data.drop(columns=["Target"])
y = data["Target"]
print(x.shape)

scaler = RobustScaler()
cols = ['Course', "Mother's qualification", "Father's qualification",
        "Admission grade", "Previous qualification (grade)", "Previous qualification"]
scaler.fit(data_copy[cols])
scaled_x = scaler.transform(data_copy[cols])

X_train, X_test, y_train, y_test = train_test_split(scaled_x, y, test_size = 0.2, stratify = y, random_state=42)



#class_weights = compute_class_weight('balanced', classes=np.unique(y_res), y=y_res)
#class_weight_dict = dict(zip(np.unique(y_res), class_weights))

# Create model
nn = Sequential([
  Flatten(input_shape=(X_train.shape[1], )),
  Dense(128, activation='relu'),
  Dense(128, activation='relu'),
  Dense(128, activation='relu'),
  Dense(64, activation='relu'),
  Dense(3, activation="softmax")
])

# Compile model
nn.compile(optimizer=Adam(0.001),
              loss=SparseCategoricalCrossentropy(),
              metrics=['accuracy'])

# Train model
#history = nn.fit(X_res, y_res, epochs = 10, batch_size=128)
history = nn.fit(X_train, y_train, epochs = 10, batch_size=128)

y_pred_probs = nn.predict(X_test, verbose=0)
y_pred = np.argmax(y_pred_probs, axis=1)
y_pred_nn = y_pred

class_rep_nn = classification_report(y_test, y_pred, target_names=['Dropout', 'Graduate', 'Enrolled'])
print("\nClassification Report (NN):\n", class_rep_nn)
cm = confusion_matrix(y_test, y_pred)
ConfusionMatrixDisplay(cm, display_labels=['Dropout', 'Graduate', 'Enrolled']).plot(cmap="Blues")
plt.title("Confusion Matrix – NN (target: Location)")
plt.tight_layout()
plt.show()

# Plot loss curve
plt.plot(history.history['loss'])
plt.title("Loss Curve")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.show()
accuracy_nn = round(nn.evaluate(X_test, y_test)[1] * 100, 2)
#Print test error
print(f"Testing Accuracy: {round(nn.evaluate(X_test, y_test)[1] * 100, 2)}%")

from itertools import cycle
from sklearn.preprocessing import label_binarize


models = [log_reg, knn, nn]
colors = cycle(['aqua', 'darkorange', 'red'])

n_classes = len(np.unique(y_test))

y_test_bin = label_binarize(y_test, classes=np.arange(n_classes))

plt.figure(figsize=(8,6))

for model, color in zip(models, colors):
    if hasattr(model, "predict_proba"):
        y_pred_proba = model.predict_proba(X_test)
    else:
        y_pred_proba = model.predict(X_test, verbose= 0)

    for i in range(n_classes):
        fpr, tpr, _ = roc_curve(y_test_bin[:, i], y_pred_proba[:, i])
        roc_auc = auc(fpr, tpr)
        plt.plot(fpr, tpr, color=color, lw=2,
                 label=f'{model.__class__.__name__} - Class {i} (AUC = {roc_auc:.2f})')

# Random guess line
plt.plot([0, 1], [0, 1], 'k--', lw=2, label='Random Guess')

plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Multiclass ROC Curve')
plt.legend(loc='lower right', fontsize=8)
plt.show()

# Prepare data for bar chart
models = ['KNN', 'Logistic Regression', 'Neural Network']
accuracies = [accuracy_knn, accuracy_log, accuracy_nn/100]

# Plot bar chart
plt.figure(figsize=(6,5))
bars = plt.bar(models, accuracies, color=['darkorange', 'aqua', 'red'])
plt.ylim(0, 1)  # Accuracy between 0 and 1
plt.ylabel('Accuracy')
plt.title('Model Accuracy Comparison')


for bar, acc in zip(bars, accuracies):
    plt.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.02, f'{acc:.2f}',
             ha='center', va='bottom')

plt.show()